import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Hero from "./components/Hero";
import Explore from "./components/Explore";
import OrderCoffee from "./components/OrderCoffee";
import SellingCoffee from "./components/SellingCoffee";
import InstantCoffee from "./components/InstantCoffee";
import Testimonial from "./components/Testimonial";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <Hero />
        <Explore />
        <OrderCoffee />
        <SellingCoffee />
        <InstantCoffee />
        <Testimonial />
        <main>{children}</main>
      </body>
    </html>
  );
}
